# Generated by Django 5.0.4 on 2024-08-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
