# Generated by Django 5.0.4 on 2024-08-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprints', '0002_alter_fingerprint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
